
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Mon Feb 13 12:27:35 PST 2006
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LESSEQUALS = 32;
  public static final int EXCEPT = 17;
  public static final int FUNCTION = 18;
  public static final int MULT = 40;
  public static final int BOOLEANLITERAL = 7;
  public static final int GREATEREQUALS = 22;
  public static final int GE = 20;
  public static final int SLASH = 52;
  public static final int EQUALS = 15;
  public static final int SLASHSLASH = 53;
  public static final int LPAREN = 37;
  public static final int GREATER = 21;
  public static final int MINUS = 38;
  public static final int LESS = 31;
  public static final int FOR = 19;
  public static final int DECIMALLITERAL = 10;
  public static final int BEFORE = 6;
  public static final int WHERE = 61;
  public static final int RPAREN = 49;
  public static final int SEMICOLON = 51;
  public static final int AND = 3;
  public static final int LT = 36;
  public static final int OR = 43;
  public static final int IN = 26;
  public static final int COMMA = 9;
  public static final int IDIV = 24;
  public static final int ORDEREDBY = 44;
  public static final int DIV = 13;
  public static final int PLUS = 45;
  public static final int IF = 25;
  public static final int QNAME = 46;
  public static final int LE = 30;
  public static final int EOF = 0;
  public static final int TOKENVARIABLE = 57;
  public static final int RETURN = 48;
  public static final int error = 1;
  public static final int INTEGERLITERAL = 27;
  public static final int LCURLY = 29;
  public static final int COLONEQUALS = 8;
  public static final int MOD = 39;
  public static final int EQ = 16;
  public static final int DECLARE = 11;
  public static final int RCURLY = 47;
  public static final int DESCENDING = 12;
  public static final int UNION = 58;
  public static final int LEXICALERROR = 34;
  public static final int ELSE = 14;
  public static final int VARIABLE = 59;
  public static final int LSQUARE = 35;
  public static final int TO = 55;
  public static final int RSQUARE = 50;
  public static final int NOTEQUALS = 42;
  public static final int LET = 33;
  public static final int THEN = 54;
  public static final int NE = 41;
  public static final int VERTICALBAR = 60;
  public static final int AFTER = 2;
  public static final int STRINGLITERAL = 56;
  public static final int ASCENDING = 5;
  public static final int INTERSECT = 28;
  public static final int AS = 4;
  public static final int GT = 23;
}

