#!/bin/sh -ev
########################################################################
##                    Px Generated File                               ##
##              Platform Express, Version 3.3.1 (BuildId: 200607071143)##
##              System Level Engineering Division                     ##
##              Mentor Graphics Corporation                           ##
##                                                                    ##
## Generated on: February 18, 2007 7:19:00 PM PST                     ##
## Generated by: saumya                                               ##
## Seamless ISS invocation script                                     ##
########################################################################

if [ -f ../pxenv.sh ] ; then . ../pxenv.sh; fi
if [ -z "$DISPLAY" ] ; then
    DISPLAY=.:0.0 
fi
display_suffix=00
DISPLAY=${DISPLAY}${display_suffix} 
export DISPLAY 
#setenv DISPLAY=goofy.ucsd.edu:0.0
${CVE_HOME}/isms/bin/xray_arm946e_sr1 \
 -inc xray.inc
