########################################################################
##                    Px Generated File                               ##
##              Platform Express, Version 3.3.1 (BuildId: 200607071143)##
##              System Level Engineering Division                     ##
##              Mentor Graphics Corporation                           ##
##                                                                    ##
## Generated on: February 18, 2007 7:19:01 PM PST                     ##
## Generated by: saumya                                               ##
## Modelsim wave command file                                         ##
########################################################################

onerror {resume}
quietly WaveActivateNextPane {} 0
radix hex
add wave /pxdefault_tb/test3_1/*
configure wave -signalnamewidth 1
