source {G:/xilinx/ise71/data/projnav/scripts/VsimStopServer.tcl}
initIPC 1200
-- Auto Generated by Project Navigator to simulate
-- HDL Bencher Annotated Test Bench
--
vlib work
onbreak {resume}
onerror {quit -code 99 -force}
onElabError {resume}
vcom -93 -explicit  Mask5.vhf
vcom -93 -explicit  Mux2_5bus.vhf
vcom -93 -explicit  Mux3_5bus_v2.vhf
vcom -93 -explicit  datapath.vhf
vcom -93 -explicit  register5.vhf
vcom -93 -explicit  regs.vhf
vcom -93 -explicit  pcounter.vhf
vcom -93 -explicit  memory16x8.vhf
vcom -93 -explicit  truthtbl.vhd
vcom -93 -explicit  machine.vhf
vcom -93 -explicit  mach_test.ant
vsim -t 1ps  -lib work mach_test
run -all
quit -force
