APPS = modelchecker
LIBNAME = SimulatorFiles
MACEPATH = ../../

include ../Makefile.common

#CXXFLAGS += -DVERIFY
#INCLUDE_DIRS += -I/home/ckillian/devel/verisoft/verisoft/bin
#LIBS += /home/ckillian/devel/verisoft/verisoft/bin/verisoft_Linux_2.x.o
#LIBS += /home/ckillian/devel/verisoft/verisoft/bin/verisoft_simul_Linux_2.x.o
