APPS = TritonShare_nogui
LIBNAME = TritonShare_nogui
MACEPATH = ../../
PRE_SERVICE_LIBS = -lTritonShare

include ../Makefile.common

INCLUDE_DIRS += -I$(MACEPATH)services/Http
LIBS += $(LIBDIRS) -lHttp -lappcommon -lmace $(CLIBS)  
