
UNIXLIB = -lD3 -lW -lP -lG -lL $(XLIB) -lm# libefence.a

DOSLIB = ..\\..\\libD3.lib ..\\..\\libW.lib ..\\..\\libP.lib ..\\..\\libG.lib ..\\..\\libL.lib $(XLIB)

WINDOW_APP = 1

#include ./Make-Solaris.pro
include ./Make.pro
