#!/bin/sh -ev
########################################################################
##                    Px Generated File                               ##
##              Platform Express, Version 3.3.1 (BuildId: 2OO607071143)##
##              System Level Engineering Division                     ##
##              Mentor Graphics Corporation                           ##
##                                                                    ##
## Generated on: February 18, 2OO7 7:18:53 PM PST                     ##
## Generated by: saumya                                               ##
## Software compile script                                            ##
########################################################################

sfhom=$hom/sw


armasm -g -cpu ARM946E-S -fpu none ${sfhom}/init.s -o ${sfhom}/init.o
armasm -g -cpu ARM946E-S -fpu none ${sfhom}/reset_vectors.s -o ${sfhom}/reset_vectors.o
armcc -c -g -O0 -cpu ARM946E-S -fpu none -I${ARMINC} ${sfhom}/interrupt_handler.c -o ${sfhom}/interrupt_handler.o
armcc -c -g -O0 -cpu ARM946E-S -fpu none -DFUNCNAME=a946Diags_1 ${sfhom}/pxCoreLib.c -o ${sfhom}/a946_pxCoreLib.o
armcc -c -g -O0 -cpu ARM946E-S -fpu none ${sfhom}/printToPort.c -o ${sfhom}/printToPort.o
armcc -c -g -O0 -cpu ARM946E-S -fpu none -I${ARMINC} ${sfhom}/retarget.c -o ${sfhom}/retarget.o
armcc -c -g -O0 -cpu ARM946E-S -fpu none -I${ARMINC} ${sfhom}/MAC_test.c -o ${sfhom}/MAC_test.o

armlink  ${sfhom}/printToPort.o \
${sfhom}/interrupt_handler.o \
${sfhom}/reset_vectors.o \
${sfhom}/init.o \
${sfhom}/retarget.o \
${sfhom}/a946_pxCoreLib.o \
${sfhom}/MAC_test.o \
 -Xref -elf -map -list MAC_test.map -info totals  -scatter ${sfhom}/scatter.scf -o MAC_test.x

fromelf -text -c -output MAC_test.disasm MAC_test.x
